<?php

namespace App;

use function foo\func;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(){
        return $this->belongsTo(Role::class,'role_id');
    }
    public function advertiser_profile(){
        return $this->hasone(AdvertiserProfile::class);
    }
    public function advertiser_company_detail(){
        return $this->hasone(AdvertiserCompanyDetail::class);
    }
    public function user_images(){
        return $this->hasOne(UserImage::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($user){
            $user->advertiser_profile()->delete();
            $user->advertiser_company_detail()->delete();
            $user->user_images()->delete();
        });
    }
}
